# Generated by Django 5.0.6 on 2024-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('shop', 'Shop'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
